global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
        labels:
          environment: lab
          service: prometheus

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
        labels:
          environment: lab
          service: node
          node: local-node

  - job_name: nomad
    metrics_path: /v1/metrics
    params:
      format:
        - prometheus
    static_configs:
      - targets:
          - nomad-server-1:4646
          - nomad-server-2:4646
          - nomad-server-3:4646
          - nomad-client-1:4646
          - nomad-client-2:4646
        labels:
          environment: lab
          service: nomad

  - job_name: "consul-server-1"
    metrics_path: "/v1/agent/metrics"
    params:
      format: ["prometheus"]
    static_configs:
      - targets: ["consul:8500"]
        labels:
          environment: "lab"
          service: "consul"
          node: "consul-server-1"
  - job_name: "consul-server-2"
    metrics_path: "/v1/agent/metrics"
    params:
      format: ["prometheus"]
    static_configs:
      - targets: ["consul2:8500"]
        labels:
          environment: "lab"
          service: "consul"
          node: "consul-server-2"

  - job_name: "consul-server-3"
    metrics_path: "/v1/agent/metrics"
    params:
      format: ["prometheus"]
    static_configs:
      - targets: ["consul3:8500"]
        labels:
          environment: "lab"
          service: "consul"
          node: "consul-server-3"

  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format:
        - prometheus
    static_configs:
      - targets:
          - vault:8200
        labels:
          environment: lab
          service: vault
          